version: "3.4"

services:
  redis:
    container_name: redis_authz_service
    image: redis:latest
    ports:
      - ${REDIS_PORT}:6379
volumes:
  pgdata:
  pgbackups:

networks:
  default:
    external:
      name: es-hs
